#!/bin/bash

# /etc/init.d/pizoneboot 

### BEGIN INIT INFO
# Provides:          pizoneboot
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts wlan network
### END INIT INFO

ifup wlan0
setssid attwifi
