#!/bin/sh
### BEGIN INIT INFO
# Provides:          pizoneboot
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initializes PiZone Nintendo spotpass
### END INIT INFO

#. /lib/lsb/init-functions

#log_daemon_msg
#log_progress_msg
#log_end_msg
#log_action_msg
#log_success_msg
#log_failure_msg
#log_warning_msg
#http://www.thegeekstuff.com/2012/03/lsbinit-script/
#PIDFILE=/var/run/my_daemon.pid

NAME=PiZone

case "$1" in 
start)
	echo "Initializing $NAME"
	ifup wlan0
	/usr/local/bin/setssid "attwifi"
;;
stop)
	#note, right now we dont need to kill it
	#since the OS will do the same
	#sudo pkill -9 -f /usr/local/bin/pizone
        echo "Stopping $NAME"
;;
*)
	echo "Usage: $0 {start|stop}"
	exit 2
esac


