#!/bin/sh
### BEGIN INIT INFO
# Provides:          pizoneboot
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initializes PiZone Nintendo spotpass
### END INIT INFO

#. /lib/lsb/init-functions

#log_daemon_msg
#log_progress_msg
#log_end_msg
#log_action_msg
#log_success_msg
#log_failure_msg
#log_warning_msg
#http://www.thegeekstuff.com/2012/03/lsbinit-script/
#PIDFILE=/var/run/my_daemon.pid

NAME=pizone
LOG_FILE="/var/log/pizone"
PIZONE_PATH=/usr/local/bin/pizone


case "$1" in 
start)

	#check if script is already running
	#pgrep -f /usr/local/bin/pizone

	//todo: this needs to be updated
	if [ "$(pgrep -f $PIZONE_PATH)" ]
	then
		echo "$NAME is already running."
		exit 2
	fi

	echo "Initializing $NAME"

	if [ -f "$LOG_FILE" ]
	then
		rm "$LOG_FILE"
	fi

	ifup wlan0
	/usr/local/bin/setssid "attwifi"
	nohup python "$PIZONE_PATH" > "$LOG_FILE" &
;;
stop)
	sudo pkill -9 -f "$PIZONE_PATH"
        echo "Stopping $NAME"
;;
*)
	echo "Usage: $0 {start|stop}"
	exit 2
esac


