#!/usr/bin/env python

import os, sys, time, subprocess

#grab the existing address and reset when this exits out
#ifconfig en1 | grep ether
#capture kill for app
#move interface into a var or command line arg

#make sure we are running as root

euid = os.geteuid()
if euid != 0:
  print "Script must be run as root"
  exit()


addresses = [
	{"address":"4E:53:50:4F:4F:43", "description":"Zelda A Link Between Worlds"},
	{"address":"4E:53:50:4F:4F:46", "description":"Main"},
	{"address":"4E:53:50:4F:4F:47", "description":"Animal Crossing New Leaf"},
	{"address":"4E:53:50:4F:4F:48", "description":"Fire Emblem"}]

#in seconds
CHANGE_INTERVAL = 60 * 10

index = 0

while True:
	item = addresses[index]
	
	print("%s : %s" % (item["description"], item["address"]))
	
	return_code = subprocess.call(["/home/pi/PiZone/scripts", item["address"]])
	
	if return_code :
		print("error running command.")
		#sys.exit()
	
	time.sleep(CHANGE_INTERVAL)
	index = index + 1
	if index >= len(addresses) :
		index = 0
	

