#!/usr/bin/env python

import os, sys, time, subprocess, json

#file path to file containing JSON data of mac addresses
ADDRESSES_JSON = "address.json"

#interval in seconds that address will be rotated
CHANGE_INTERVAL = 60 * 10

if os.geteuid() != 0:
  print "Script must be run as root"
  sys.exit()

try:
	json_data = open(ADDRESSES_JSON)
except IOError:
	print("Error loading %s" % ADDRESSES_JSON)
	sys.exit()


try:
	addresses = json.load(json_data)
except ValueError:
	print("Error parsing %s" % ADDRESSES_JSON)
	sys.exit()
finally:
	json_data.close()


index = 0

while True:
	item = addresses[index]
	
	print("%s : %s : %s" % (item["description"], item["address"], item["ssid"]))
	
	return_code = subprocess.call(["sudo", "/home/pi/PiZone/scripts/cmac", item["address"], item["ssid"]])
	
	if return_code :
		print("error running command.")
		sys.exit()
	
	time.sleep(CHANGE_INTERVAL)
	index = index + 1
	if index >= len(addresses) :
		index = 0
	

